version: '2'
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
        stdin_open: true
        tty: true
        links:
          - SwooleDistributed
    SwooleDistributed:
        container_name: swooledistributed
        image: mataotao/swooledistributed
        ports:
            - "9091:9091"
            - "9092:9092"
            - "9093:9093"
            - "9999:9999"
        volumes:
            - ./:/usr/src/sd
        stdin_open: true
        tty: true
        links:
          - redis
          - mysql
        depends_on:
          - redis
          - mysql
        command: php /usr/src/sd/bin/start_swoole_server.php start
    redis:
         container_name: redis
         image: redis
         ports:
           - 6379
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - "3306:3306"
#        volumes:
#            - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: manager

        stdin_open: true
        tty: true

